apiVersion: v1
kind: Pod
metadata:
  name: filebrowser
spec:
  containers:
  - name: main
    image: docker.io/filebrowser/filebrowser:s6
    ports:
      - containerPort: 80
        hostPort: 8080
    env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    volumeMounts:
    - name: srv
      mountPath: /srv:Z
    - name: database
      mountPath: /database:Z
    - name: config
      mountPath: /config:Z
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true

  volumes:
  - name: srv
    hostPath:
      path: ./srv
      type: DirectoryOrCreate
  - name: database
    hostPath:
      path: ./db
      type: DirectoryOrCreate
  - name: config
    hostPath:
      path: ./config
      type: DirectoryOrCreate
  - name: localtime
    hostPath:
      path: /etc/localtime
      type: File

